[package]
name = "combo_vec"
version = "0.1.0"
edition = "2021"
authors = ["VirxEC"]
description = "An array that can be resized at runtime, without moving any data off the stack"
readme = "README.md"
repository = "https://github.com/VirxEC/extendable_array"
license = "GPL-3.0-only"
categories = ["data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
